\documentclass{article}
\usepackage{graphicx}

\title{Computing Homework 5}
\author{Group 5}


\begin{document}
\maketitle
\date{}

\section{Exercises 99-105, 109, 112-126}


\textbf{100}
<<>>=
upper_count = function(vec) {
  return(nchar(gsub("[^::A-Z::]","", vec)))
}

upper_count(c("FOO", "bar", "baZ"))
@


\textbf{101}
<<>>=
strrev = function(string) {
  reversed = rev(strsplit(string, "")[[1]])
  return(paste(reversed, collapse = ""))
}

strrev("ABC")
@



\end{document}
