---
title: "Computing HW #1 Group 5"
output: html_notebook
---

1.
```{r}
170166719 %% 31079
```

2.
```{r}
exp_sum = function(n) {
  r = 1.08
  x = seq(1, n, 1)
  result = sum(r^x)
  return(result)
  }

exp_quick = function(n) {
  r = 1.08
  result = ((r^(n+1)-1)/(r-1)) - 1
  return(result)
}

writeLines("Values using the sum:")
exp_sum(10)
exp_sum(20)
exp_sum(30)
exp_sum(40)

writeLines("Values using the quick formula:")
exp_quick(10)
exp_quick(20)
exp_quick(30)
exp_quick(40)

writeLines("Quick formula results for n=1 to n=100")
exp_quick_vec = exp_quick(c(1:100))
exp_quick_vec
```


3.
```{r}
lin_sum = function(n) {
  x = seq(1, n, 1)
  result = sum(x)
  return(result)
  }

lin_quick = function(n) {
  result = (n*(n+1))/2
  return(result)
}

writeLines("Values using the sum:")
lin_sum(100)
lin_sum(200)
lin_sum(400)
lin_sum(800)

writeLines("Values using the quick formula")
lin_quick(100)
lin_quick(200)
lin_quick(400)
lin_quick(800)


writeLines("Quick formula results for n=1 to n=100")
lin_quick_vec = lin_quick(c(1:100))
lin_quick_vec
```


4.
```{r}
sq_sum = function(n) {
  x = seq(1, n, 1)
  result = sum(x^2)
  return(result)
  }

sq_quick = function(n) {
  result = (n*(n+1)*(2*n+1))/6
  return(result)
}

writeLines("Values using the sum:")
sq_sum(100)
sq_sum(200)
sq_sum(400)
sq_sum(800)

writeLines("Values using the quick formula:")
sq_quick(100)
sq_quick(200)
sq_quick(400)
sq_quick(800)

writeLines("Quick formula results for n=1 to n=100")
sq_quick_vec = sq_quick(c(1:100))
sq_quick_vec
```

5.
```{r}
log_sum = function(n) {
  x = seq(1, n, 1)
  result = sum(1/x)
  return(result)
  }

log_quick = function(n) {
  result = log(n)
  return(result)
}

writeLines("Values using the sum:")
log_sum(100)
log_sum(200)
log_sum(400)
log_sum(800)

writeLines("Values using the quick formula:")
log_quick(100)
log_quick(200)
log_quick(400)
log_quick(800)

writeLines("Quick formula results for n=1 to n=100")
log_quick_vec = log_quick(c(1:100))
log_quick_vec
```

```{r}
log_sum((10^5)) - log((10^5))
log_sum((10^6)) - log((10^6))
log_sum((10^7)) - log((10^7))
```

The limit of s_n - log(n) is Euler's constant (gamma), approx equal to 0.5772.



6. 
```{r}
v = rep(0:4, each = 5)
v

v2 = rep(seq(1,5, by=1), 5)
v2
```


7. 
```{r}
v = rep(seq(1,5), times=5) + rep(seq(0,4), each=5)
v
```


8. 
```{r}
asc_func = function(n) {
  value = rep(0:n, 0:n)
  return(value)
}

asc_func(5)
```


9.
```{r}
numbers = c(3,5,8,10,12)
dump("numbers", file = "numbers.R")
rm(numbers)
ls()
```

```{r}
source("numbers.R")
numbers
```


10.
```{r}
letter_file = function(file_name, file_type)
  {
  alphabet = LETTERS[1:26]
  write.csv(alphabet, file = paste(file_name, file_type, sep="."))
}

letter_file("letters", "csv")
letter_file("letters", "txt")
```


11. TODO
```{r}

```

12.
```{r}
sign = function(number) {
  if (number == 0){
    return ("Zero; Neither Positive nor Negative")
  }
  else if (number > 0){
    return(TRUE)
  } 
    else {
      return(FALSE)
  }
}

sign(1)
sign(0)
sign(-1)
```


13.
```{r}
pi_abs = function(number) {
  if (abs(number) == pi){
    return ("Equal to Pi")
  }
  else if (abs(number) > pi){
    return("Greater than Pi")
  } 
    else {
      return("Less than Pi")
  }
}
```


14.
```{r}
means = function(x,y,type) {
  if (type == "geometric"){
    if (x*y >= 0){
      mean = sqrt((x*y))
      return(mean)
    }
    else {
      return("Error; input values must have the same sign.")
    }
  }
  
  if (type == "harmonic"){
    if (x > 0 && y > 0 ){
      mean = 2/ ((1/x) + (1/y))
      return(mean)
    }
    else {
      return("Error; the harmonic mean is undefined if either value is 0 or negative")
    }
  }
}

means(0,4,"harmonic")
means(2,4,"geometric")
```

15. 
```{r}
string_length = function(s1, s2) {
  s1_len = nchar(s1)
  s2_len = nchar(s2)
  
  if (s1_len == s2_len){
    return("The strings have the same length")
  }
    else if (s1_len > s2_len){
      return(paste(s1, " is longer")) 
      }
  
    else if (s1_len < s2_len){
      return(paste(s2, " is longer"))
    }
  else {
    return("Error")
  }
}

string_length("foo", "foos")
string_length("3455", "2")
string_length("1", "1")
```


16.
```{r}
character = function(s) {
  for (i in 1:nchar(s)) {
    writeLines(s)
  }
}

character("computing")
```


17.
```{r}
reverse_nat = function(x) {
  for (i in x:1){
    print(i)
  }
}

reverse_nat(10)
```

18.
```{r}
is_divisible <- function(x,y)
{ if (x%%y == 0)
  {
    return(TRUE)
  }
  else
  {
    return(FALSE)
  }
}
```

```{r}
is_divisible(3,4)
```
```{r}
is_divisible(8,4)
```


19.
```{r}
sum_of_digits <- function(n)
{
  vector_of_digits <- c()
  while (n!=0) {
    if (n%%10 == 0) 
    {
      n <- n/10
    }
    else
    {
      vector_of_digits <- c(vector_of_digits, n%%10)
      n <- n- n%%10
    }
  }
  return(sum(vector_of_digits))
}

```
```{r}
sum_of_digits(121)
```
```{r}
sum_of_digits(345)
```
```{r}
sum_of_digits(655)
```


20. 
```{r}
number_of_digits <- function(n_vec)
{
  vector_of_digits <- c()
  
  for(i in 1:length(n_vec))
  {
    while (n_vec[i]!=0) {
      if (n_vec[i]%%10 == 0) 
      {
        n_vec[i] <- n_vec[i]/10
      }
      else
      {
        vector_of_digits <- c(vector_of_digits, n_vec[i]%%10)
        n_vec[i] <- n_vec[i]- n_vec[i]%%10
      }
    }
  }
  
  return(length(vector_of_digits))

}  
```

```{r}
number_of_digits(123)
```

```{r}
number_of_digits(c(1,23,45,678))
```

20. (alternative solution)
```{r}
digit_count = function(x) {
  counter = 0 
  for (i in x) {
    counter = counter + nchar(i)
  }
  return(counter)
}

digit_count(13)
digit_count(c(1,234,4564))
```


21.
```{r}
sum_squares_two_largest_numbers <- function(x1,x2,x3)
{
  input_decreasing <- sort(c(x1,x2,x3), decreasing = TRUE)
  return (sum(input_decreasing[c(1,2)]^2))
}

sum_squares_two_largest_numbers(20,10,35)
```

22.
```{r}
unique_real_root_cubic <- function(a,b,c)
{
  p <- (3*b-a^2)/3
  cat("p=", p, " ")
  
  q <- (2*a^3)/27 - (a*b/3) + c
  cat("q=", q, " ")
  
  D <- (p/3)^3+(q/2)^2
  cat("D=", D, " ")
  
  n_root <- function(x,n){
    sign(x) * abs(x)^(1/n)
  }
  
  if(D>0)
  {
    x <- -(a/3) + n_root(-(q/2)+sqrt(D),3) + n_root(-(q/2)-sqrt(D),3)
  } else
  {
    print("Error: There is no unique real solution! Discriminant is not positive!")
  }
  cat("The unique real root of this cubic equation is", x, " ")
  return(x)
}
```

```{r}
unique_real_root_cubic(3,5,7)
```


23. 
```{r}
# a 
factorial <- function(n)
{
  fact <- prod(1:n)
  return(fact)
}

factorial(10)  

factorial(50)

factorial(100)

factorial(1000)

# b
bin_coefficient <- function(n,m)
{
  result <- factorial(n)/(factorial(m)*factorial(n-m))
  return(result)
}

bin_coefficient(4,2)

bin_coefficient(50,20)

bin_coefficient(5000,2000)


# c
log_factorial = function(n) {
  counter = 0
  for (i in 2:n){
    counter = counter + log(i)
  }
  return(counter)
}

log_binomial = function(n, k) {
  return(exp(sum(log_factorial(n), -log_factorial(k), -log_factorial(n-k))))
}

log_binomial(4,2)
log_binomial(50,20)
log_binomial(5000, 2000)
```

24.

```{r}
# Try gamma() for n=200
gamma(200)
```
This approach fails because the value is too large for R to compute and store in base 10. 

```{r}
# implementing log. gamma function
rho_n <- function(n)
{
  return(exp(lgamma((n-1)/2) - (lgamma(1/2) + lgamma((n-2)/ 2))))
}
```

```{r}
rho_n(200)
```

```{r}
rho_n(2000) / sqrt(2000)
rho_n(4000) / sqrt(4000)
rho_n(6000) / sqrt(6000)
rho_n(10000) / sqrt(10000)

#rho_n(n)/sqrt(n) tends to ~0.3988
```
