---
title: "R Notebook"
output: html_notebook
---

73-74


77.
```{r}
log_via_expansion = function(x, max_error,p_count=1){
  p = seq(1:p_count)
  computation = sum((-1)^(p-1)*(((x-1)^p)/p))
  if(abs(computation-log(x))<=max_error){
    return(c(computation,p_count))
  }else{
    return(Recall(x, max_error, p_count+1))
  }
}

# How many terms in the expansion are required to calculate log(1.5) with an error of at most 10^-16?
log_via_expansion(1.5, 1/10^16)

# How many terms are required to calculate log(2) with an error of at most 10^16?
log_via_expansion(2, 1/10^16) # not applicabale

#Use the fact that log(2) = 2 log(√2) to suggest a better way of calculating log(2).
log_via_expansion(sqrt(2), (1/10^16)/2)
```

78.
```{r}

```

79.
```{r}
for(i in 1:10000000){
  sum_ex79 = sum_ex79 + 1/10^i
}
cat(sum_ex79, "\n")
```

80.
```{r}
sum_ex80=0
for(i in 0:10000000){
  sum_ex80 = sum_ex80 + (((-1)**(i))/(i+1))
}
cat(sum_ex80, "\n")
```

81.
```{r}
result_ex81 = 0 
for(i in 0:1000000){
  result_ex81 = result_ex81+1/((2*(2*i+1)-1)*(2*(2*i+1)+1))
}

cat(result_ex81, "\n")
```

82.
```{r}
# Diclaimer I used a different version of Wallis'product -> it can be found in the following paper:
#http://mat.uab.cat/pubmat/fitxers/download/FileType:pdf/FolderName:v50(1)/FileName:50106_01.pdf
wallis_pi_approx <- function(n){
  i =1
  wallis_prod = (2*i-1)*(2*i+1)/(2*i*2*i)
  for(i in 2:n){
    wallis_prod = wallis_prod * (2*i-1)*(2*i+1)/(2*i*2*i)
  }
  return((wallis_prod**-1)*2)
}

wallis_pi_approx(1)
wallis_pi_approx(10)
wallis_pi_approx(100)
wallis_pi_approx(1000)
wallis_pi_approx(10000)
wallis_pi_approx(100000)
```

83.
```{r}
states = state.new
multiple_words = function(char_vec) {
  return(length(grep(" ", char_vec)))
}

multiple_words(states)
state.name
```


84.
```{r}
states = state.name
states = gsub(" ","",states, ignore.case = TRUE) #don't count spaces as characters
vowel_count = nchar(gsub("[^aeiou]","",states, ignore.case = TRUE))
consonant_count = nchar(gsub("[aeiou]","",states, ignore.case = TRUE))

sum(vowel_count > consonant_count) #number of states with more vowels than consonants
states
```


85.
```{r}
states = state.name
s_count = nchar(gsub("[^s]","",states, ignore.case = TRUE))
sum(s_count > 3) #number of states with more than 3 s
states
```


86.
This question is ambiguous as what constitutes a double vowel; any vowel twice, or the same vowel twice? Below is a solution to both, respectively.
```{r}
states = state.name
sum(grepl("[aeiou]{2}", states, ignore.case = TRUE))

sum(grepl("(ee)|(aa)|(ii)|(oo)|(uu)", states, ignore.case = TRUE))
```

87.
```{r}
color = colors()
sum(grepl("red", color, ignore.case = TRUE))
```

88.
```{r}
#Version that considers space as a character
text_char = function(url) {
  text = readLines(url)
  counts = sort(table(unlist(strsplit(text, ""), use.names=FALSE)), decreasing=FALSE)
  return(cat("The most frequent character is", names(counts)[length(counts)], ", which appears" ,max(counts), "times."))
}     

text_char("http://statmath.wu.ac.at/~hornik/index.html")


#Version that does not consider space as a character
text_char_2 = function(url) {
  text = readLines(url)
  text = gsub(" ", "", text, ignore.case=TRUE)
  counts = sort(table(unlist(strsplit(text, ""), use.names=FALSE)), decreasing=FALSE)
  return(cat("The most frequent character is", names(counts)[length(counts)], ", which appears" ,max(counts), "times."))
}

text_char_2("http://statmath.wu.ac.at/~hornik/index.html")
```
78.
```{r}
sine=function(x){
  "we know that the sine has a periodicity of 2 pi and we can use it to reduce the number 
  of recursions for large x and also make it more accurate as dividing x 
  multiple times gives potential representation errors"
  
  x=x%%(2*pi) 
  if(abs(x)<0.1*pi){
    return(x)
  }else{
    return(3*Recall(x/3)-4*Recall(x/3)^3)
  }
}
sine(pi)
sine(4*pi)
sine(0)
sine(1)
sine(1000000000)

cat("
    To implement this we need roughly log(2/0.1)/log(3)=", log(2/0.1)/log(3), "steps which means we need at most 3 steps. This translates to 2^3=8 different x values.
    ")
```

89.
```{r}
wc = function(url) {
  text = readLines(url)
  text = gsub("[[:punct:]]", " ", text, ignore.case = TRUE)
  text = gsub("[0-9]", " ", text, ignore.case=TRUE)
  words = strsplit(text, " ")
  counts = sort(table(unlist(words)))
  counts = counts[names(counts) != ""]
  return(cat("The most frequent word is", names(counts)[length(counts)], ", which appears" ,max(counts), "times."))
  
}

wc("http://statmath.wu.ac.at/~hornik/index.html")
```


90.
```{r}
word_freq = function(word, url) {
  text = readLines(url)
  text = gsub("[[:punct:]]", " ", text, ignore.case = TRUE)
  text = gsub("[0-9]", " ", text, ignore.case=TRUE)
  text = tolower(text)
  words = strsplit(text, " ")
  counts = sort(table(unlist(words)))
  counts = counts[names(counts) != ""]
  return(counts[[tolower(word)]][1])
  
}

word_freq("div","http://statmath.wu.ac.at/~hornik/index.html")
```


91.
```{r}
numbertobinary <- function(x) {
  i <- 0
  string <- numeric(32)
  while(x > 0) {
    string[32 - i] <- x %% 2
    x <- x %/% 2
    i <- i + 1 
  }
  first <- match(1, string)
  string[first:32] 
}

numbertobinary(6)
```

92.
```{r}
letters_in_state = function(letter_string) {
  state = sample(state.name, 1)
  letter_string_raw = as.list(strsplit(letter_string, "")[[1]])
  print(state)
  
  counter = 0
  for (i in letter_string_raw) {
    if(grepl(i, state, ignore.case=TRUE) == TRUE) {
      counter = counter + 1
    }
  }
  
  if (counter == length(letter_string_raw)){
    return(TRUE)
  }
  else {
    return(FALSE)
  }
}


letters_in_state("Co")
letters_in_state("A")
letters_in_state("u")

```
94

```{r}
col_prod=function(mat){
  cols=ncol(mat)
  products=numeric(cols)
  for(i in 1:cols){
    products[i]=prod(mat[,i])
  }
  return(products)
}

coef_from_roots=function(z){
  if(length(z)==1){
    return(-z)
  }
  n=length(z)
  c=numeric(length(z))
  "consider that (x-a)(x-b)(x-c)=x^3-(a+b+c)x^2+(ab+bc+ca)x-abc. 
  we see that beta_i is the sum of the products of all possible (n-i) draws of the n roots, times (-1)^(n-i) "
  # we calculate coefficients from n to 1 and then return reversed array
  for(i in 1:n){
    combinations=combn(z, i)
    parts=col_prod(combinations)
    c[i]=(-1)^i*sum(parts)
  }
  return(rev(c))
}
coef_from_roots(c(1, 2, 4))
coef_from_roots(c(5))

```

97
```{r}
polyderiv=function(beta){
  beta_deriv=beta*(seq(1:length(beta))-1)
  return(beta_deriv[-1])
}
polyderiv(c(1, 1, 1, 1, 1))

infl_points=function(beta){
  return(polyroot(polyderiv(polyderiv(beta))))
}
infl_points(c(1, 1, 1, 1, 1))
infl_points(c(1, 1, 1, 1))
infl_points(c(0, 0, 0, 1))
=
```
